### ISSUE TITLE
Permission denied on sprite.txt when running sample scene

### ISSUE THREAD

**Issue by hennlo** [TigrisCallidus/Qisge#32]
## Issue
Game crashes with python traceback error  `PermissionError: [Errno 13] Permission denied` on _input.txt_ or _sprite.txt_

## Environemnt
**OS**: Windows 10 - 2004 (64 Bit)
**Unity**: Checked with _2020.3.9.f1_ & _2019.4.27.f1_

## Reproducing the issue
When starting and running the scene: `QisgeMain`  in a freshly created Unity project.
The crash will occur after an arbitrary time, couldn't figure out any pattern yet. Either when waiting roughly a minute and doing nothing. Or when playing and holding down buttons while pressing others.
But again no obvious pattern visible to me.
The only thing visible before the crash is an error in Unity console. See supporting information 2.

I know it clearly states "permission denied", but I think this is still coming from qisge.py.
Is it maybe because I'm holding a button pressed? And therefore the file is locked for that moment and if another qisge.upate() function is beeing processed it leads to the creash?

Since the error somewhat originates out of qisge.py/run.py I thought I'd let you know

### 1 - In Game screenshot
![grafik](https://user-images.githubusercontent.com/64148462/120003262-e07a9000-bfd5-11eb-828b-cdce0a01e8bb.png)

### 2 - Unity Console Error
`IOException: Sharing violation on path E:\Documents\Develpoment\game_dev\Unity\projects\first\qisgeFirst\Assets\StreamingAssets\Exchange\sprite.txt
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean checkHost) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.StreamReader..ctor (System.String path) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
(wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
System.IO.File.ReadAllText (System.String path) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
GameManager.CheckFiles () (at Assets/Qisge/GameManager.cs:147)
GameManager.Update () (at Assets/Qisge/GameManager.cs:126)
`

**Comment by TigrisCallidus** [comment]
I had this error in the past, but I thought I fixed it. It does come up, wehn Unity locks a file, while python tries to read it.

I thought I got rid of all file locks. Thank you for reporting this, I will look into it.

**Comment by TigrisCallidus** [comment]
I just pushed an update, which might solve the bug because it improves performance. 

I could not reproduce the bug even without the update, so its a bit hard to say.

**Comment by hennlo** [comment]
Thanks for the information and the quick fix, that worked indeed. 🏁 

_NOTE_
One thing I noted that this behavior occurred when Qisge/Unity is running on an HDD.
Due to the slower disk I/O  this might  lead to the extended locks on the shared files.

I now was able to verify when using the "old" release on an SSD instead, the bug did not occur at all.
